#include <stdio.h>

#define I_THINK_I_SHALL_NEVER_SEE int main(void) {
#define A_POEM_LOVELY_AS_A_TREEE printf("A beautiful poem\n");
#define A_TREE_WHOS_HUNGRY_MOUTH_IS_PRESSED return 0;
#define AGAINST_THE_EARTHS_SWEET_FLOWING_BREAST }

I_THINK_I_SHALL_NEVER_SEE
A_POEM_LOVELY_AS_A_TREEE
A_TREE_WHOS_HUNGRY_MOUTH_IS_PRESSED
AGAINST_THE_EARTHS_SWEET_FLOWING_BREAST