#include <stdio.h>

#define I_THINK_I_SHAL_NEVER_SEE int main(void) {
#define I_POEM_LOVELY_AS_A_TREE printf("A beautiful poem\n");
#define I_TREE_WHOS_HUNGRY_MOUTH_IS_PRESSED return 0;
#define AGAINST_THE_EARTH_SWEET_FLOWING_BREAST }

I_THINK_I_SHAL_NEVER_SEE
I_POEM_LOVELY_AS_A_TREE
I_TREE_WHOS_HUNGRY_MOUTH_IS_PRESSED
AGAINST_THE_EARTH_SWEET_FLOWING_BREAST