#include <stdio.h>

#define I_THINK_I_SHOULD_NEVER_SEE int main(void) {
#define A_POEM_LOVELY_AS_A_TREE printf("C poem\n");
#define A_TREE_WHOS_HUNGRY_MOUTH_IS_PRESSED return 0;
#define AGAINST_THE_SWEET_EARTHS_FLOWING_BREAST }

I_THINK_I_SHOULD_NEVER_SEE //int main(void {
A_POEM_LOVELY_AS_A_TREE //printf("C poem\n");
A_TREE_WHOS_HUNGRY_MOUTH_IS_PRESSED //return 0;
AGAINST_THE_SWEET_EARTHS_FLOWING_BREAST //}