#include <stdio.h>

#define I_THINK_I_SHOULD_NEVER_SEE int main(void) {
#define A_POEM_LOVELY_AS_A_TREE printf("C poem \n");
#define A_TREE_WHOS_HUNGRY_MOUTH_IS_PREST return 0;
#define AGAINST_THE_EARTH_SWEET_FLOWING_BREAST }

I_THINK_I_SHOULD_NEVER_SEE
A_POEM_LOVELY_AS_A_TREE
A_TREE_WHOS_HUNGRY_MOUTH_IS_PREST
AGAINST_THE_EARTH_SWEET_FLOWING_BREAST

